# Generated by Django 5.0.6 on 2024-05-31 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название компании')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='Почта')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Адрес')),
                ('number_1', models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер телефона')),
                ('number_2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Резервный номер телефона')),
                ('inn', models.CharField(blank=True, max_length=100, null=True, verbose_name='ИНН')),
                ('gos_num', models.CharField(blank=True, max_length=100, null=True, verbose_name='ОГРН')),
            ],
        ),
    ]
